productName = "SkyCtl"
version = "0.1.0"
identifier = "space.skyctl.app"

[bundle]
active = true
targets = ["appimage", "msi", "app"]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../dist"

[[app.windows]]
title = "SkyCtl"
width = 1280
height = 720
center = true
decorations = true
hiddenTitle = true

[app.security]
csp = ""
