name: "Continuous Integration"

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.86.0

      - name: Install tauri-cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tauri-cli
          version: ^2.0.0

      - name: Load Cached pnpm Store
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: ${{ matrix.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-node-

      - name: Load Cached Cargo Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-

      - name: Install frontend dependencies
        run: |
          pnpm install

      - name: Build Tauri App
        run: |
          pnpm tauri build --verbose

      - name: Publish to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src-tauri/target/release/bundle/dmg/*.dmg
          asset_name: SkyCtl-macos-${{ matrix.arch }}.dmg
          asset_content_type: application/x-apple-diskimage

  linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: arm64        

    container:
      image: ghcr.io/skyctl-space/devcontainer:25.05.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Load Cached pnpm Store
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: ${{ matrix.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-node-

      - name: Load Cached Cargo Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-

      - name: Install frontend dependencies
        run: |
          pnpm install

      - name: Build Tauri App
        run: |
          pnpm tauri build --verbose

      - name: Publish to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src-tauri/target/release/bundle/appimage/*.AppImage
          asset_name: SkyCtl-linux-${{ matrix.arch }}.AppImage
          asset_content_type: application/vnd.appimage

  windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
          - os: windows-11-arm
            arch: arm64        


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pnpm 
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install tauri-cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tauri-cli
          version: ^2.0.0

      - name: Load Cached pnpm Store
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: ${{ matrix.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-node-

      - name: Load Cached Cargo Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-

      - name: Install frontend dependencies
        run: |
          pnpm install

      - name: Build Tauri App
        run: |
          pnpm tauri build --verbose

      - name: Publish to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src-tauri/target/release/bundle/nsis/*.exe
          asset_name: SkyCtl-windows-${{ matrix.arch }}.exe
          asset_content_type: application/x-msdownload

